Add colors to output
ilya112358/SvenskaJa pull request #9
Opened 2023-01-13 13:46 UTC by ilya112358

Please, check if these colors work in linux shell and look ok for you.

2023-01-16 13:33 UTC, fyodor7878 commented
I had to make python 3.11 from source since Debian has 3.9 still. But that did not help anyway since I used sqlite library from Debian repo which, again, is not updated (3.34) and does not support new commands that you use. I worked it out eventually but I suggest that you fall back with those commands since they are not widely supported yet.

As for colors, I think, it is a nice touch, but expect them to look different on different platforms. In my environment I would prefer them to be bright, the normal ones are too dark (see screenshot for comparison). 
![SvenskaJa Screenshot 2023-01-16 131407](https://user-images.githubusercontent.com/111524119/212688676-60b9da75-7da9-42e3-b82d-b2a795b851e7.png)
Also, don't forget to add colorama to requirements.txt.

2023-01-17 12:34 UTC, fyodor7878 commented
You asked before about Unicode under Linux:
https://www.cl.cam.ac.uk/~mgk25/unicode.html

On Mon, 16 Jan 2023 at 16:06, I Bo ***@***.***> wrote:

> I see. In Windows cmd normal colors are closer to bright colors and bright
> colors are almost identical to normal (esp white). Ok, I think, I'll put it
> on hold until I come up with some strategy.
>
> Regarding the sqlite problem, I see your point and address this asap.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ilya112358/SvenskaJa/pull/9#issuecomment-1384189461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2S3SF3N3EZBGJMW43N7M4DWSVPV5ANCNFSM6AAAAAAT2NV6II>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-01-18 15:19 UTC, ilya112358 commented
You should be able to run it on 3.9 now. I decided to leave red and green as they are but brighten yellow.

2023-01-18 16:24 UTC, fyodor7878 requested changes
One suggestion, otherwise looks ok

2023-01-18 16:24 UTC, fyodor7878 commented on practice.py
>                      input()
Unite it into one: input(f'\n{verb}') to remove extra empty line which now looks too empty, I think.

2023-01-19 10:57 UTC, fyodor7878 approved these changes
Good to go

2023-01-19 13:24 UTC, merged